# Generated by Django 6.0.7 on 2026-07-12 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('sort_order', models.IntegerField(verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Free text, displayed verbatim.', max_length=150, verbose_name='job title')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disputed', 'Disputed'), ('removed', 'Removed')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text="The person's employer for this work (outsourcing/freelance).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='games.company')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='contributions.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Vouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches', to='contributions.contribution')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouches_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vouches',
            },
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['discipline', 'game'], name='contrib_discipline_game'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='contribution_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(('game__isnull', False), ('company__isnull', False), _connector='OR'), name='contribution_game_or_company'),
        ),
        migrations.AddConstraint(
            model_name='vouch',
            constraint=models.UniqueConstraint(condition=models.Q(('voter__isnull', False)), fields=('contribution', 'voter'), name='unique_vouch_per_voter'),
        ),
    ]
