# Generated by Django 6.0.7 on 2026-08-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_seed_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending verification'), ('disputed', 'Disputed'), ('removed', 'Removed')], default='active', max_length=20, verbose_name='status'),
        ),
    ]
