# Generated by Django 6.0.7 on 2026-08-21 18:50

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_contribution_status_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country'),
        ),
    ]
