# Generated by Django 6.0.7 on 2026-07-12 18:24

import accounts.models
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Required Postgres extension for typo-tolerant search (pg_trgm) —
        # this app migrates first, so every later GIN trgm index can rely on it.
        TrigramExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('display_name', models.CharField(help_text='Real name or pseudonym — real identity is never required.', max_length=100, verbose_name='display name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('role', models.CharField(choices=[('member', 'Member'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='member', max_length=20, verbose_name='role')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Gate: must be set before the user can create contributions.', null=True, verbose_name='email verified at')),
                ('profile_public', models.BooleanField(default=True, help_text='False makes the profile invisible everywhere (safety valve).', verbose_name='public profile')),
                ('contactable', models.BooleanField(default=True, help_text='Allow contact via the relay. The email itself is never exposed.', verbose_name='contactable')),
                ('open_to_work', models.BooleanField(default=False, help_text='Badge + recruiter search filter. Independent from contactable.', verbose_name='open to work')),
                ('avatar', models.CharField(blank=True, default='', help_text='Object key in the S3 bucket.', max_length=500, verbose_name='avatar')),
                ('bio', models.TextField(blank=True, default='', verbose_name='bio')),
                ('location', models.CharField(blank=True, default='', max_length=150, verbose_name='location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('work_email', models.EmailField(max_length=254, verbose_name='work email')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn URL')),
                ('message', models.TextField(blank=True, default='', verbose_name='message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recruiter_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['display_name'], name='user_display_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='recruiterapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='one_pending_application_per_user'),
        ),
    ]
