# Generated by Django 6.0.7 on 2026-07-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', help_text='Stored in the S3 bucket (object key). Deleted on account deletion.', max_length=500, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
