# Generated by Django 6.0.7 on 2026-07-15 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_login',
            field=models.CharField(blank=True, default='', help_text='Declared GitHub handle — not verified (same trust model as a LinkedIn link).', max_length=39, verbose_name='GitHub login'),
        ),
        migrations.CreateModel(
            name='GitHubSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, default='', max_length=39)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('public_repos', models.PositiveIntegerField(blank=True, null=True)),
                ('followers', models.PositiveIntegerField(blank=True, null=True)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('profile_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('never_fetched', 'Never fetched'), ('ok', 'OK'), ('not_found', 'Not found'), ('error', 'Error')], default='never_fetched', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubYearlyContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('total_commits', models.PositiveIntegerField(default=0)),
                ('total_contributions', models.PositiveIntegerField(default=0)),
                ('private_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField()),
                ('is_final', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_yearly_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year'), name='one_row_per_user_year')],
            },
        ),
    ]
