# Generated by Django 6.0.7 on 2026-07-15 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_login',
            field=models.CharField(blank=True, default='', help_text='Declared GitHub handle — not verified (same trust model as a LinkedIn link).', max_length=39, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9](?:[A-Za-z0-9]|-(?=[A-Za-z0-9])){0,38}$', 'Enter a valid GitHub username.')], verbose_name='GitHub login'),
        ),
    ]
