# Generated by Django 6.0.7 on 2026-07-16 12:33

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_github_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', help_text='Predefined list — powers the people-search country filter.', max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='city / region'),
        ),
    ]
