# Generated by Django 6.0.7 on 2026-08-20 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_user_email_ci_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='image')),
                ('thumbnail', models.ImageField(upload_to='portfolio/thumbs/', verbose_name='thumbnail')),
                ('caption', models.CharField(blank=True, default='', max_length=140, verbose_name='caption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile image',
                'verbose_name_plural': 'profile images',
                'ordering': ['-created_at'],
            },
        ),
    ]
