# Generated by Django 6.0.7 on 2026-08-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_email',
            field=models.EmailField(blank=True, default='', help_text='Shown on your public profile to anyone. Leave empty to be reachable only through Rollcall messages.', max_length=254, verbose_name='public contact email'),
        ),
    ]
