# Generated by Django 6.0.7 on 2026-07-12 18:24

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_company_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='slug')),
                ('logo_url', models.URLField(blank=True, default='', max_length=500, verbose_name='logo URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('manual', 'Manual')], default='seed', max_length=20, verbose_name='source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_companies', to=settings.AUTH_USER_MODEL)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='games.company')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=300, verbose_name='alias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='games.company')),
            ],
            options={
                'verbose_name_plural': 'company aliases',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('steam_appid', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='release date')),
                ('summary', models.TextField(blank=True, default='', verbose_name='summary')),
                ('cover_url', models.URLField(blank=True, default='', max_length=500, verbose_name='cover URL')),
                ('igdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IGDB user rating')),
                ('igdb_aggregated_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IGDB critics rating')),
                ('steam_positive_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Steam positive %')),
                ('steam_review_count', models.IntegerField(blank=True, null=True, verbose_name='Steam review count')),
                ('slug', models.SlugField(blank=True, max_length=520, unique=True, verbose_name='slug')),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('igdb_live', 'IGDB live'), ('manual', 'Manual')], default='seed', max_length=20, verbose_name='source')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synced at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_games', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('publisher', 'Publisher'), ('porting', 'Porting'), ('supporting', 'Supporting')], max_length=20, verbose_name='role')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_links', to='games.company')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='games.game')),
            ],
            options={
                'verbose_name_plural': 'game companies',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='companies',
            field=models.ManyToManyField(related_name='games', through='games.GameCompany', to='games.company'),
        ),
        migrations.CreateModel(
            name='GameEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.engine')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='engines',
            field=models.ManyToManyField(related_name='games', through='games.GameEngine', to='games.engine'),
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.genre')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', through='games.GameGenre', to='games.genre'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='company_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='companyalias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['alias'], name='company_alias_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='companyalias',
            constraint=models.UniqueConstraint(fields=('company', 'alias'), name='unique_company_alias'),
        ),
        migrations.AddConstraint(
            model_name='gamecompany',
            constraint=models.UniqueConstraint(fields=('game', 'company', 'role'), name='unique_game_company_role'),
        ),
        migrations.AddIndex(
            model_name='gameengine',
            index=models.Index(fields=['engine', 'game'], name='gameengine_engine_game'),
        ),
        migrations.AddConstraint(
            model_name='gameengine',
            constraint=models.UniqueConstraint(fields=('game', 'engine'), name='unique_game_engine'),
        ),
        migrations.AddIndex(
            model_name='gamegenre',
            index=models.Index(fields=['genre', 'game'], name='gamegenre_genre_game'),
        ),
        migrations.AddConstraint(
            model_name='gamegenre',
            constraint=models.UniqueConstraint(fields=('game', 'genre'), name='unique_game_genre'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='game_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['release_date'], name='games_game_release_b822ea_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['steam_positive_pct'], name='games_game_steam_p_113690_idx'),
        ),
    ]
